defaults:
  - model: pix2poly   # Default model
  - dataset: inria   # Default dataset

device: 'cuda'
checkpoint: /data/rsulzer/${.model.name}_outputs/${.dataset.name}/best_valid_metric.pth
output_dir: /data/rsulzer/${.model.name}_outputs/${.dataset.name}

subset: null
