name: pix2poly
type: vit_small_patch${.patch_size}_${.input_size}.dino
input_size: 224
input_height: ${.input_size}
input_width: ${.input_size}
patch_size: 8
num_patches: null
sinkhorn_iterations: 100
tokenizer: 
    num_bins: ${..input_size}
    shuffle_tokens: false
    n_vertices: 192
    max_len: null
    pad_idx: null
    generation_steps: null
batch_size: 32

label_smoothing: 0.0
vertex_loss_weight: 1.0
perm_loss_weight: 10.0

start_epoch: 0
num_epochs: 100
milestone: 0
save_best: True
save_latest: True
save_every: 10
val_every: 1

learning_rate: 1e-4
weight_decay: 1e-4